# Generated by Django 4.0 on 2024-09-17 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='api.Coupon'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='api.Teacher'),
        ),
        migrations.AlterField(
            model_name='cartorderitem',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='api.Coupon'),
        ),
    ]
